### ISSUE TITLE
Automatically detect camera type

### ISSUE THREAD

**Issue by sevku** [labthings/picamerax#10]
Is there a way to programmatically detect which camera is connected? I especially want to automatically detect noir cameras.

**Comment by jtc42** [comment]
My understanding is that the noir camera is identical hardware to the normal v2 but with the IR filter removed. If this is the case then I don’t think it’s possible to distinguish via software.

What you can do is use the revision property to get the sensor model at least. See https://picamera.readthedocs.io/en/release-1.13/api_camera.html#picamera.PiCamera.revision

Given this is either possible using the upstream function, or way outside of the scope of this fork (I.e. somehow detecting the presence of an IR filter) I’m going to close this issue for now,
