### ISSUE TITLE
Question: variable frame rate while recording video

### ISSUE THREAD

**Issue by morrowwm** [labthings/picamerax#21]
Is it possible to change the framerate while recording? I'm working on a surveillance script. My thought was low framerate when there is no motion, then high framerate while motion is detected. Something like:

```
import os, psutil
import time
import picamerax
import picamerax.array
import numpy as np
import io

camera = picamerax.PiCamera()
motion_detected = False
motion_num = 0
motion_size = 0.0

class MotionDetector(picamerax.array.PiMotionAnalysis):
    def analyse(self, a):
        global last_pic_time, motion_detected, motion_num, motion_size
        ampl = np.sqrt(
            np.square(a['x'].astype(np.float)) +
            np.square(a['y'].astype(np.float)))
        motion_max = ampl.max()
        motion_quantile = np.quantile(ampl, 0.999)
        motion_num = (ampl > motion_quantile).sum()
        motion_size = ampl.mean()
        now = time.time()
        # If quantile > 50, then say we've detected motion
        
        if motion_quantile > 10.0 and motion_max > 50.0:
            print('    Motion at time: %.0f N: %d max: %.1f m: %.1f q %.1f' % (now, motion_num, motion_max, motion_size, motion_quantile))
            motion_detected = True
        else:
            motion_detected = False

with MotionDetector(camera) as motionDetector:
    try:
        pid = psutil.Process(os.getpid())
        camera.resolution = (1280,720)
        camera.framerate = 5
        camera.shutter_speed = 0
        # camera.exposure_mode = 'night'
        # give camera time to settle down
        time.sleep(2)
        camera.start_recording('/mnt/survey/surveil.h264', format='h264', motion_output=motionDetector)
        camera.annotate_background = picamerax.Color('black')
        while True:
            memused = pid.memory_info().rss/(1024)
            if motion_detected:
                camera.framerate = 25
                camera.annotate_text = "movement %s %d %f" % (tstamp, motion_num, motion_size)
            else:
                tstamp = time.strftime("%Y-%m-%d_%H%M%S")
                camera.annotate_text = "%s %d %f" % (tstamp, motion_num, motion_size)

    except KeyboardInterrupt as e:
        camera.close()
        pass 
    finally:
        print("Done")
```
This does not work, it's saying the framerate can't be changed while recording?

> ~/scripts $ python3 var_frames.py 
>     Motion at time: 1642164983 N: 1 max: 68.1 m: 0.1 q 56.0
> Done
> Traceback (most recent call last):
>   File "var_frames.py", line 51, in <module>
>     camera.framerate = 25
>   File "/usr/local/lib/python3.7/dist-packages/picamerax/camera.py", line 2367, in _set_framerate
>     self._check_recording_stopped()
>   File "/usr/local/lib/python3.7/dist-packages/picamerax/camera.py", line 744, in _check_recording_stopped
>     raise PiCameraRuntimeError("Recording is currently running")
> picamerax.exc.PiCameraRuntimeError: Recording is currently running

**Comment by morrowwm** [comment]
P.S. My intent could be accomplished by modifying https://picamerax.readthedocs.io/en/latest/recipes2.html#splitting-to-from-a-circular-stream to 

1.  output the before and after video with timestamps on each motion event
2. also continual output images at a low frequency
3. assemble the images and small motion videos together into one large daily video. 

This wouldn't be as efficient, obviously.

**Comment by jtc42** [comment]
This may be better to raise upstream as this isn't specific to any of the additions in picamerax, however as far as I'm aware you can't change framerate during a recording. What you may need to do is start recording at a low framerate, then when motion is detected, stop the recording, up the framerate, then start a new recording.

You may be able to avoid that by doing some clever stuff with splitter ports, but without spending more time on the problem I couldn't give you any details.

Hope that helps a bit! Given this isn't actually an issue with the repository code, I'll close this issue if that's ok?

**Comment by morrowwm** [comment]
Yes, please close this. Thanks for the insight.
