### ISSUE TITLE
Lens shading with stereo capture

### ISSUE THREAD

**Issue by abingham** [labthings/picamerax#7]
I'm interested in using lens shading with stereo image capture, and I wanted to see if it's even supposed to be supported. 

My initial, perhaps naive experiments seem to show that it doesn't work. I construct my cameras something like `PiCamera(stereo_mode='side-by-side')`. I then use [the calibration function](https://github.com/rwb27/openflexure_microscope_software/blob/better_shading_correction/openflexure_microscope/utilities/recalibrate.py) by @rwb27 to generate a shading table. I then use that table in subsequent stereo image captures. The results I get look pretty clearly incorrect.

FWIW, everything seems to work fine if I don't capture stereo images. The table is calculated properly, and it does good lens shading compensation when I use it. So it seems there's a problem with stereo mode and lens shading, but I'm not sure if it's:

1. That the table calculation routine does work properly for stereo images (though I don't see anything in it that should be problematic).
2. That picamerax isn't actually able to use lens shading tables in stereo mode.
3. Something else entirely.

Does anyone have any advice or insight?

**Comment by abingham** [comment]
I've noticed that I can get lens shading to work on one camera in a stereo image. I first calculate a shading table using a `PiCamera` in mono mode (i.e. `stereo_mode == 'none'`). I then use that shading table to capture an image using a `PiCamera` in stereo mode. When I do this, half of the stereo image (i.e. the image from one sensor) has the table applied to it while the other doesn't.

I've looked through the `PiCamera` source and I don't see anything that would let me apply the table to both cameras. So is this just an oversight in the implementation? 

I'll keep looking, but any hints would be great. Thanks!

**Comment by abingham** [comment]
I've found that if I calculate a shading table from a non-stereo `PiCamera` and then use that table in a stereo `PiCamera`, the table is applied - in some way - to both sensors. For one sensor (the left hand sensor in the side-by-side capture) the shading adjustment seems to be working well. For the right hand image, the image has clearly been adjusted (i.e. it's different that an image taken with no lens shading table), but it's not as good as the left hand.

So it seems that the lens shading table *is* being applied to both images. But either it's applied differently to the right-hand, or the table is not correct for the right-hand lens. Both lenses are identical, though there might be differences due to focus settings or something.

In any event, I'm still eager to know if this is expected to work at all. Can anyone confirm that lens shading is expected to work in stereo capture mode? I just want to make sure I'm not wasting my time trying to sort it out. Thanks!

**Comment by jtc42** [comment]
@rwb27 is probably the best person to answer this

**Comment by rwb27** [comment]
Hi @abingham sorry to chime in incredibly late - I am embarrassingly bad at keepoing up with my github notifications :(  I'm afraid I don't know any more than appears in the `picamera` docs, as I've never tried stereo imaging.  I'm not even sure how it works - a quick search of the `raspivid` source suggests it's all handled inside the GPU firmware, so the chances of a definitive answer from me are zero.  If you ask in one of the RPi forums, you might find more out from one of the people that works on the firmware, though they are incredibly busy so don't be surprised if it takes a while to get a response...

My gut feeling is that I wouldn't expect it to work, but I'm prepared to be surprised!  It may also be that it *could* work but would require more to be exposed in the API than we currently have access to.
